// <auto-generated />
using System;
using FCG.Payments.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCG.Payments.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCG.Payments.Domain.Entities.Playment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_PAGAMENTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<int>("GameId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_GAME");

                    b.Property<string>("MethodPayment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1)")
                        .HasColumnName("COD_PAGAMENTO");

                    b.Property<string>("StatusPayment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1)")
                        .HasColumnName("COD_STATUS");

                    b.Property<int>("UserId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_USUARIO");

                    b.HasKey("Id");

                    b.ToTable("TB_PAGAMENTO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
